spring:
  datasource:
    url: jdbc:postgresql://$IP/$DB
    username: $USER_NAME
    password: $PASSWORD

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
